"""empty message

Revision ID: 03bfeeb1b89d
Revises: d63e6468bfe0
Create Date: 2021-07-20 13:46:26.732697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03bfeeb1b89d'
down_revision = 'd63e6468bfe0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trucks', sa.Column('size', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trucks', 'size')
    # ### end Alembic commands ###
