"""empty message

Revision ID: 4851c5079c5b
Revises: 48e15e092d1f
Create Date: 2021-07-11 21:40:03.174766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4851c5079c5b'
down_revision = '48e15e092d1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('subject', sa.String(length=100), nullable=False))
    op.drop_index('ix_messages_email', table_name='messages')
    op.drop_index('ix_messages_name', table_name='messages')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_messages_name', 'messages', ['name'], unique=False)
    op.create_index('ix_messages_email', 'messages', ['email'], unique=False)
    op.drop_column('messages', 'subject')
    # ### end Alembic commands ###
