"""empty message

Revision ID: 48e15e092d1f
Revises: 3681969f406e
Create Date: 2021-07-10 18:32:49.696286

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '48e15e092d1f'
down_revision = '3681969f406e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('email', sa.String(length=64), nullable=False))
    op.add_column('comments', sa.Column('name', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_comments_email'), 'comments', ['email'], unique=False)
    op.drop_column('comments', 'rimage')
    op.drop_column('comments', 'respondent')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('respondent', mysql.VARCHAR(length=10), nullable=False))
    op.add_column('comments', sa.Column('rimage', mysql.VARCHAR(length=150), nullable=True))
    op.drop_index(op.f('ix_comments_email'), table_name='comments')
    op.drop_column('comments', 'name')
    op.drop_column('comments', 'email')
    # ### end Alembic commands ###
