"""empty message

Revision ID: 6b43ddd9292f
Revises: c2023404fe79
Create Date: 2021-07-22 19:44:56.758137

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b43ddd9292f'
down_revision = 'c2023404fe79'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('quotes')
    op.drop_table('sales')
    op.drop_table('customer')
    op.drop_table('employee')
    op.drop_table('spares')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spares',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('spare_img', sa.VARCHAR(length=150), nullable=True),
    sa.Column('description', sa.VARCHAR(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('employee',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fname', sa.VARCHAR(length=72), nullable=False),
    sa.Column('lname', sa.VARCHAR(length=72), nullable=False),
    sa.Column('pwd', sa.VARCHAR(length=72), nullable=False),
    sa.Column('uname', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pwd')
    )
    op.create_table('customer',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('fname', sa.VARCHAR(length=72), nullable=False),
    sa.Column('lname', sa.VARCHAR(length=72), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('spare_img', sa.VARCHAR(length=150), nullable=True),
    sa.Column('description', sa.VARCHAR(length=150), nullable=True),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('employee_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('quotes',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=150), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=150), nullable=False),
    sa.Column('branch', sa.VARCHAR(length=150), nullable=False),
    sa.Column('model', sa.VARCHAR(length=150), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
