"""empty message

Revision ID: 848ec8059fbe
Revises: a2b9f4d8c42b
Create Date: 2021-07-22 22:20:10.359006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '848ec8059fbe'
down_revision = 'a2b9f4d8c42b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'uname')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('uname', sa.VARCHAR(length=20), nullable=False))
    # ### end Alembic commands ###
