"""empty message

Revision ID: d63e6468bfe0
Revises: 140b6b168725
Create Date: 2021-07-20 12:30:12.730700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd63e6468bfe0'
down_revision = '140b6b168725'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_date_sent', table_name='messages')
    op.drop_table('messages')
    op.drop_index('ix_subscribers_email', table_name='subscribers')
    op.drop_table('subscribers')
    op.drop_index('ix_comments_date_posted', table_name='comments')
    op.drop_index('ix_comments_email', table_name='comments')
    op.drop_table('comments')
    op.drop_table('images')
    op.drop_index('ix_posts_date_posted', table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('slug', sa.VARCHAR(length=100), nullable=False),
    sa.Column('postImage', sa.VARCHAR(length=150), nullable=True),
    sa.Column('body', sa.TEXT(), nullable=False),
    sa.Column('views', sa.INTEGER(), nullable=True),
    sa.Column('count', sa.INTEGER(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=30), nullable=False),
    sa.Column('date_posted', sa.DATETIME(), nullable=True),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_posts_date_posted', 'posts', ['date_posted'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('filename', sa.VARCHAR(length=150), nullable=True),
    sa.Column('thumbnail', sa.VARCHAR(length=150), nullable=True),
    sa.Column('file_size', sa.VARCHAR(length=150), nullable=True),
    sa.Column('file_width', sa.VARCHAR(length=150), nullable=True),
    sa.Column('file_height', sa.VARCHAR(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('message', sa.VARCHAR(length=2000), nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), nullable=False),
    sa.Column('email', sa.VARCHAR(length=64), nullable=False),
    sa.Column('date_posted', sa.DATETIME(), nullable=True),
    sa.Column('post_id', sa.INTEGER(), nullable=True),
    sa.Column('status', sa.BOOLEAN(), nullable=True),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_comments_email', 'comments', ['email'], unique=False)
    op.create_index('ix_comments_date_posted', 'comments', ['date_posted'], unique=False)
    op.create_table('subscribers',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_subscribers_email', 'subscribers', ['email'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('email', sa.VARCHAR(length=64), nullable=False),
    sa.Column('subject', sa.VARCHAR(length=100), nullable=False),
    sa.Column('message', sa.TEXT(), nullable=False),
    sa.Column('status', sa.BOOLEAN(), nullable=True),
    sa.Column('date_sent', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_date_sent', 'messages', ['date_sent'], unique=False)
    # ### end Alembic commands ###
