"""empty message

Revision ID: e58d65b54195
Revises: 03bfeeb1b89d
Create Date: 2021-07-20 17:10:56.730114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e58d65b54195'
down_revision = '03bfeeb1b89d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trucks', sa.Column('status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trucks', 'status')
    # ### end Alembic commands ###
